# Generated by Django 4.0.4 on 2022-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=200, verbose_name='quesion')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
