# Generated by Django 4.0.4 on 2022-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='affective_zone',
            field=models.CharField(default='Manage a Mathematics Containing Situation', max_length=200, verbose_name='affective_zone'),
        ),
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.CharField(default='Data Handling & Chance ', max_length=200, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='question', max_length=200, verbose_name='question'),
        ),
    ]
