# Generated by Django 3.2.3 on 2022-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_affective_zone_question_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='I interpret information from a variety of sources to form an opinion about a work/hobby situation.', max_length=200, verbose_name='question'),
        ),
    ]
