# Generated by Django 4.0.4 on 2022-06-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
    ]
